### PR TITLE
added branch alias

### PR DESCRIPTION
**Pull request by staabm**

### CODE REVIEW

**Comment by kelunik** [comment]
I don't like branch aliases, they always tend to get out of date.

**Comment by staabm** [comment]
only when branch aliases exist I can reference a non-released version - when required.

**Comment by kelunik** [comment]
No, you can always depend on `dev-master` as well. We release versions often enough so it's not really necessary IMO.

**Comment by staabm** [comment]
> No, you can always depend on dev-master as well. We release versions often enough so it's not really necessary IMO.

depending on dev-master can result into breakage. with branch alias I can reference a version which at least adheres to semantic versioning

**Comment by kelunik** [comment]
In theory, yes. In practice these aliases tend to get outdated and your stuff breaks anyway. If you depend on `dev-master` for a bugfix, ping the maintainers and a bug-fix will be released. If you depend on `dev-master` because of a new feature, ping the maintainers and a feature release can be tagged. If you depend on `dev-master` because of a rewrite with breaking changes, relying on a branch alias doesn't improve anything.

**Comment by Danack** [comment]
Also, in the rare cases where there is a bug fix in dev-master, that you urgently need, and for whatever reason a release isn't made, you can specify the exact commit that contains the bug fix, which should be the safest option.

**Pull request closed without merging**
